---
- name: Управление учетными записями
  hosts: vbox
  vars:
    user: test_user  # Имя новой учетной записи
    password: "1234"  # Пароль новой учетной записи
    level_privileges: 63  # Уровень привилегий для Astra Linux, максимальный - 63
    level_become: true  # Права sudo дял tasks
  tasks:
    - name: Определить группу для sudo в зависимости от семейства ОС
      set_fact:
        sudo_group: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"

    - name: Проверка существования группы wheel
      command: getent group wheel
      register: wheel_group_check
      ignore_errors: true

    - name: Установить sudo_group в sudo, если wheel не существует
      set_fact:
        sudo_group: "sudo,astra-admin"
      when: wheel_group_check.rc != 0

    - name: Добавление УЗ c правами root в систему
      user:
        name: "{{ user }}"
        state: present
        create_home: yes
        shell: /bin/bash
        groups: "{{ sudo_group }}"
        password: "{{ password | password_hash('sha512') }}"
      become: "{{ level_become }}"

    - name: Назначение максимального уровня привилегий
      shell: /bin/bash -c "pdpl-user {{ user }} -i {{ level_privileges }}"
      when: sudo_group == 'sudo,astra-admin'  # Будет выполнено только в ОС семейства Debian
      ignore_errors: true
      become: "{{ level_become }}"  # Используем привилегии root
